# You must customize the following variables:
# - DOCKER_REPOSITORY: ...

variables:
  DOCKER_NAME: {{ repo_name }}
  DOCKER_REPOSITORY: your-docker-repo  # TODO: Replace with actual Docker registry
  UPDATE_IMAGE_TAG: .{{ repo_name }}.deployment.image.tag

include:
  - project: 'gitlab-ci/templates'
    ref: main
    file:
      - 'node/test.yml'
      - 'docker/build.yml'
      - 'helm/update.yml'