apiVersion: v1
kind: Service
metadata:
  name: {%raw%}{{ include "{{ repo_name }}.fullname" . }}{%endraw%}
  labels:
    {%raw%}{{- include "{{ repo_name }}.labels" . | nindent 4 }}{%endraw%}
spec:
  type: {%raw%}{{ .Values.service.type }}{%endraw%}
  ports:
    - port: {%raw%}{{ .Values.service.port }}{%endraw%}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {%raw%}{{- include "{{ repo_name }}.selectorLabels" . | nindent 4 }}{%endraw%}